// Clarity AI — Learn More Page View & Controller

export function renderLearnMore() {
  return `
    <main class="container" style="padding-block: var(--spacing-xl); display: flex; flex-direction: column; gap: var(--spacing-xl);">
      <div class="section-header text-center" style="max-width: 800px; margin: 0 auto;">
        <span class="badge badge--accent">Cognitive Science</span>
        <h1 style="font-size: 40px; margin-top: var(--spacing-sm);">The Psychology of Clarity</h1>
        <p style="font-size: 18px; color: var(--text-secondary); margin-top: var(--spacing-sm);">Why guided questioning and Socratic reflection yield stronger neural pathways and better follow-through than copying lists of options.</p>
      </div>

      <!-- Cognitive Science Insights Grid -->
      <div class="grid grid-cols-3 gap-lg" style="margin-top: var(--spacing-md);">
        <div class="settings-card" style="padding: var(--spacing-lg); border-radius: var(--radius-lg); border: 1px solid var(--border-color); background-color: var(--bg-secondary); display: flex; flex-direction: column; gap: 12px;">
          <div class="feature-card__icon" style="color: var(--error); background-color: rgba(239, 68, 68, 0.08); width: 40px; height: 40px; border-radius: var(--radius-sm); display: flex; align-items: center; justify-content: center;"><i data-lucide="zap-off" style="width: 20px; height: 20px;"></i></div>
          <h3 style="font-size: 18px; font-weight: 600;">The Illusion of Competence</h3>
          <p style="font-size: 14px; line-height: 1.6; color: var(--text-secondary);">
            When we query standard LLMs for immediate answers, our brains receive quick steps that feel satisfying but carry zero structural memory. Because we skipped the neural effort of brainstorming, we build an "illusion of competence." When it comes to taking action, we fail to execute.
          </p>
        </div>

        <div class="settings-card" style="padding: var(--spacing-lg); border-radius: var(--radius-lg); border: 1px solid var(--border-color); background-color: var(--bg-secondary); display: flex; flex-direction: column; gap: 12px;">
          <div class="feature-card__icon" style="color: var(--accent); background-color: var(--accent-light); width: 40px; height: 40px; border-radius: var(--radius-sm); display: flex; align-items: center; justify-content: center;"><i data-lucide="help-circle" style="width: 20px; height: 20px;"></i></div>
          <h3 style="font-size: 18px; font-weight: 600;">The Generation Effect</h3>
          <p style="font-size: 14px; line-height: 1.6; color: var(--text-secondary);">
            Cognitive psychology has demonstrated that information generated by your own mind is integrated and recalled up to 10x better. By prompting you to describe the situation, Clarity AI leverages the Socratic method to turn technology into a mirror of your own intelligence.
          </p>
        </div>

        <div class="settings-card" style="padding: var(--spacing-lg); border-radius: var(--radius-lg); border: 1px solid var(--border-color); background-color: var(--bg-secondary); display: flex; flex-direction: column; gap: 12px;">
          <div class="feature-card__icon" style="color: var(--success); background-color: rgba(34, 197, 94, 0.08); width: 40px; height: 40px; border-radius: var(--radius-sm); display: flex; align-items: center; justify-content: center;"><i data-lucide="target" style="width: 20px; height: 20px;"></i></div>
          <h3 style="font-size: 18px; font-weight: 600;">Mitigating Choice Fatigue</h3>
          <p style="font-size: 14px; line-height: 1.6; color: var(--text-secondary);">
            Faced with high-stress career or project decisions, our prefrontal cortex experiences severe cognitive fatigue when presented with long lists of choices. Restricting the AI output to exactly <strong>one concrete, immediate next step</strong> clears the fog and sparks immediate momentum.
          </p>
        </div>
      </div>

      <!-- Socratic Cycle Science Box -->
      <div class="grid grid-cols-2 gap-xl" style="background-color: var(--bg-secondary); border: 1px solid var(--border-color); padding: var(--spacing-xl); border-radius: var(--radius-lg); align-items: center;">
        <div>
          <h3 style="font-size: 22px; font-weight: 600; margin-bottom: 12px;">The Three-Stage Cycle</h3>
          <p style="font-size: 15px; line-height: 1.6; color: var(--text-secondary); margin-bottom: var(--spacing-md);">
            Our thinking coach uses a structured cycle mapped directly to human problem-solving neurology:
          </p>
          <ul style="display: flex; flex-direction: column; gap: 12px; font-size: 14px; color: var(--text-secondary); padding: 0; margin: 0;">
            <li style="list-style: none; line-height: 1.6;">
              <strong style="color: var(--accent);">1. Reflect:</strong> Focuses on self-disclosure and emotional identification to define the core variables.
            </li>
            <li style="list-style: none; line-height: 1.6;">
              <strong style="color: var(--accent);">2. Focus:</strong> Exposes cognitive blind spots and separates what you can control from external outcomes.
            </li>
            <li style="list-style: none; line-height: 1.6;">
              <strong style="color: var(--accent);">3. Take Action:</strong> Forces prioritization of a single micro-task to dissolve inertia.
            </li>
          </ul>
        </div>
        <div style="display: flex; justify-content: center; align-items: center;">
          <i data-lucide="brain" style="width: 140px; height: 140px; color: var(--accent); opacity: 0.85;"></i>
        </div>
      </div>
    </main>
  `;
}

export function initLearnMore() {
  // Setup learn more page logic if any
}
